spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.timeout=24h

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
