spring.datasource.url=jdbc:postgresql://localhost:5432/pactum
spring.datasource.username=pactum
spring.datasource.password=pactum

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.timeout=24h

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
